% Creates the info panel. You probably don't want to call this directly,
% but rather GetCalibrationInfoPanel (which calls this).

function h = CreateCalibrationInfoPanel
    global CBPdata params CBPInternals;

%%%%%%%%%%%%%%%%%%%%%%%%%%
% MAIN PANEL

    h = uipanel(figure(params.plotting.calibration_figure), ...
        'Tag', 'calibration_info', 'Position', [0 0.96 1 0.04]);

    % experiment name label
    experimentname = uicontrol('Parent', h, ...
                               'Tag', 'infopanel_experimentname', ...
                               'Style', 'edit', ...
                               'Enable', 'inactive', ...
                               'String', "  Name: " + CBPdata.experimentname, ...
                               'HorizontalAlignment', 'left', ...
                               'Units', 'normalized', ...
                               'Position', [0 0 1/2 1]);

    % number of channels
    numchans       = uicontrol('Parent', h, ...
                               'Tag', 'infopanel_numchans', ...
                               'Style', 'edit', ...
                               'Enable', 'inactive', ...
                               'String', "Channels: " + CBPdata.rawdata.nchan, ...
                               'HorizontalAlignment', 'center', ...
                               'Units', 'normalized', ...
                               'Position', [1/2 0 1/8 1]);

    % sample rate
    samplerate     = uicontrol('Parent', h, ...
                               'Tag', 'infopanel_samplerate', ...
                               'Style', 'edit', ...
                               'Enable', 'inactive', ...
                               'String', "fs: " + round(1/CBPdata.rawdata.dt) + " Hz", ...
                               'HorizontalAlignment', 'center', ...
                               'Units', 'normalized', ...
                               'Position', [5/8 0 1/8 1]);

    % recording length
    reclength      = uicontrol('Parent', h, ...
                               'Tag', 'infopanel_reclength', ...
                               'Style', 'edit', ...
                               'Enable', 'inactive', ...
                               'String', "Length: " + ...
                                         (CBPdata.rawdata.dt * ...
                                          CBPdata.rawdata.nsamples) + ...
                                         " seconds", ...
                               'HorizontalAlignment', 'center', ...
                               'Units', 'normalized', ...
                               'Position', [3/4 0 1/8 1]);

    % recording length
    numcells       = uicontrol('Parent', h, ...
                               'Tag', 'infopanel_cellplot', ...
                               'Style', 'pushbutton', ...
                               'String', 'Cell Plot Info...', ...
                               'FontWeight', 'bold', ...
                               'HorizontalAlignment', 'center', ...
                               'Units', 'normalized', ...
                               'Position', [7/8 0 1/8 1], ...
                               'Callback', @(varargin) GetCellInfoFigure);
