% Opens up a dialog to import a file.
function result = ImportFileDialog
    global dialogwin dialogresult CBPInternals;
    % this is false until the user chooses something
    dialogresult = false;

    % if the window is already open, close it
    if ~isempty(dialogwin) && isvalid(dialogwin)
        close(dialogwin);
    end

    dialogwin = dialog('Name', 'Import Data', ...
                       'Units', 'Normalized', ...
                       'Position', [0.25 0.25 0.5 0.5]);

    % get file formats
    filestr = "";
    for n=1:length(CBPInternals.filetypes.import)
        if n ~= 1
            filestr = filestr + sprintf("\n");
        end
        filestr = filestr + "* " + ...
                  CBPInternals.filetypes.import{n}.desc + ": " + ...
                  CBPInternals.filetypes.import{n}.ext;
    end
    message = {'', ...
        'To begin using CBP, you must import a data file.', ...
        'This may overwrite your existing workspace, so be careful!', ...
        '', ...
        '=====================================================', ...
        'Data can be imported in any of the following formats:', ...
        filestr, ...
        '=====================================================', ...
        '', ...
        'We have also provided two demo data sets for you to use to evaluate the software:', ...
        '', ...
        '*Quiroga1*', ...
        'Simulated data example, single electrode', ...
        'from: Quiroga et. al., Neural Computation, 16:1661-1687, 2004', ...
        '', ...
        '*Harris1*', ...
        'Real data example, tetrode + one ground-truth intracellular electrode, rat hippocampus', ...
        'from: Harris et. al., J. Neurophysiology, 84:401-414, 2000', ...
        '', ...
        '', ...
        'Please select an import option below:'};

    txt1 = uicontrol('Parent',dialogwin,...
        'Style','text',...
        'Units','normalized',...
        'Position',[0 0 1 1],...
        'ForegroundColor',[0 0 0],...
        'BackgroundColor',[1 1 1],...
        'String', message);

    quiroga1 = uicontrol('Parent',dialogwin,...
        'Style', 'Pushbutton', ...
        'Units', 'normalized', ...
        'Position',[0 0 1/3 0.1],...
        'String','Quiroga1', ...
        'Callback', @(varargin) choosefile('Quiroga1'));

    harris1 = uicontrol('Parent',dialogwin,...
            'Style', 'Pushbutton', ...
            'Units', 'normalized', ...
            'Position',[1/3 0 1/3 0.1],...
            'String','Harris1',...
            'Callback', @(varargin) choosefile('Harris1'));

    fromfile = uicontrol('Parent',dialogwin,...
        'Style', 'Pushbutton', ...
        'Units', 'normalized', ...
        'Position',[2/3 0 1/3 0.1],...
        'String','Import From File',...
        'Callback', @(varargin) choosefile('File'));

    % Wait for d to close before running to completion
    uiwait(dialogwin);

    result = dialogresult;
    clear global dialogwin dialogresult;
end

% Responds to the button press in the above.

function choosefile(id)
    global dialogresult CBPdata CBPInternals;
    try
        switch id
            case 'Quiroga1'
                % Demo case.
                % Simulated data: single electrode.
                % From: Quiroga et. al., Neural Computation, 16:1661-1687, 2004.
                fprintf('Loading Quiroga dataset 1...\n');
                filename = './example_data/C_Easy1_noise015.mat';
                indx = 1;   % the index for a CBP file
            case 'Harris1'
                % Demo case.
                % Real data: tetrode + one ground-truth intracellular electrode,
                % rat hippocampus
                % From: Harris et. al., J. Neurophysiology, 84:401-414, 2000.
                fprintf('Loading Harris dataset 1...\n');
                filename = './example_data/harris_d533101.mat';
                indx = 1;   % the index for a CBP file
            otherwise
                % Open file dialog

                % put together the file types (or what MATLAB calls
                % "filterspec" from the calls to RegisterFileFormat in
                % BasicSetup
                filterspec = {};
                for n=1:length(CBPInternals.filetypes.import)
                    filterspec{n,1} = char(CBPInternals.filetypes.import{n}.ext);
                    filterspec{n,2} = char(CBPInternals.filetypes.import{n}.desc + ...
                                      " (" + filterspec{n,1} + ")");
                end

                [file,path,indx] = uigetfile(filterspec, 'Import Dataset');

                % If they hit cancel, just return
                if file == 0
                    return;
                end

                % Hand it off to ParseFile
                filename = fullfile(path,file);
                fprintf("\nLoading %s (%s)...\n", filename, ...
                        CBPInternals.filetypes.import{indx}.desc);
        end

        % Double check file actually exists
        if ~exist(filename,'file')
            error('File doesn''t exist!');
        end

        % Once we have the file info, call the subparser,
        % and run initialize session (pass filename)
        SubParserFunc = CBPInternals.filetypes.import{indx}.funchandle;
        SubParserFunc(filename);
        InitializeSession(filename);
    catch err
        delete(gcf);
        errordlg(sprintf("There was an error while processing.\n" + ...
                         "This may be because of a malformed file, or " + ...
                         "because some parameter in the file is set " + ...
                         "incorrectly.\n" + ...
                         "\n" + ...
                         "Error message is below:\n" + ...
                         "===\n%s\n" + ...
                         "===\n\nMore detail in the command window.", ...
                         err.message), "Processing Error", "modal");
        dialogresult = false;
        rethrow(err);
    end

    dialogresult = true;    % Terminates loop in main function
    delete(gcf);            % Closes modal dialog
end
