% Creates the status bar. You probably don't want to call this directly,
% but rather GetCalibrationStatus (which calls this).

function h = CreateCalibrationStatus
    global params;

%%%%%%%%%%%%%%%%%%%%%%%%%%
% MAIN PANEL
    h = uipanel(figure(params.plotting.calibration_figure), ...
        'Tag', 'calibration_sb', 'Position', [0 0 1 0.05]);
    RegisterTag(h);

    repeatbutton = uicontrol(h, 'Tag', 'calibration_sb_repeat', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Repeat', ...
                                'Units', 'normalized', ...
                                'Position', [0 0 0.25 1], ...
                                'Callback', @(varargin) CBPRepeat);

    nextbutton   = uicontrol(h, 'Tag', 'calibration_sb_next', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Next', ...
                                'Units', 'normalized', ...
                                'Position', [0.25 0 0.25 1], ...
                                'Callback', @(varargin) CBPNext);

    reviewbutton = uicontrol(h, 'Tag', 'calibration_sb_review', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Go to Post-Analysis', ...
                                'Units', 'normalized', ...
                                'Position', [0.5 0 0.25 1], ...
                                'Callback', @(varargin) CBPReview);
                            
    RegisterTag(repeatbutton);
    RegisterTag(nextbutton);
    RegisterTag(reviewbutton);
    
    % Note - due to MATLAB bug, if we set the component as Visible=off
    % during uicontrol creation, it will have the wrong look and feel
    % when we turn it back on. So we set it after
    set(reviewbutton, 'Visible', 'off');

%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONTEXT MENU
    % New context menu
    optionbutton = popupmenu(h, ...
       "ButtonArgs", {'Tag', 'calibration_sb_options', ...
                      'Style', 'pushbutton', ...
                      'FontSize', 14, ...
                      'String', 'Options', ...
                      'Units', 'normalized', ...
                      'Position', [0.85 0 0.15 1]}, ...
          "Entries", {{'Label', 'New Session...', ...
                       'Callback', @(varargin) menuchoice('newsession')}, ...
                      {'Label', 'Export...', ...
                       'Callback', @(varargin) menuchoice('export')}, ...
                      {'Label', 'Change Parameters...', ...
                       'Callback', @(varargin) menuchoice('params')}});
    RegisterTag(optionbutton);
end

function menuchoice(choice)
    switch choice
        case 'newsession'
            CBPBegin;    % Note this is the "initial" CBP script
        case 'export'
            ExportFileDialog;
        case 'params'
            GetParamsFigure;
        otherwise
            error('INTERNAL ERROR: invalid menu choice');
    end
end