% Creates the status bar. You probably don't want to call this directly,
% but rather GetCalibrationStatus (which calls this).

function h = CreateCalibrationStatus
    global params;

    h = uipanel(figure(params.plotting.calibration_figure), ...
        'Tag', 'calibration_sb', 'Position', [0 0 1 0.05]);

    repeatbutton = uicontrol(h, 'Tag', 'calibration_sb_repeat', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Repeat', ...
                                'Units', 'normalized', ...
                                'Position', [0 0 0.25 1], ...
                                'Callback', @(varargin) CBPRepeat);

    nextbutton   = uicontrol(h, 'Tag', 'calibration_sb_next', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Next', ...
                                'Units', 'normalized', ...
                                'Position', [0.25 0 0.25 1], ...
                                'Callback', @(varargin) CBPNext);

    reviewbutton = uicontrol(h, 'Tag', 'calibration_sb_review', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Go to Post-Analysis', ...
                                'Units', 'normalized', ...
                                'Position', [0.5 0 0.25 1], ...
                                'Callback', @(varargin) CBPReview);

    paramsbutton = uicontrol(h, 'Tag', 'calibration_sb_params', ...
                                'Style', 'pushbutton', ...
                                'FontSize', 14, ...
                                'String', 'Params', ...
                                'Units', 'normalized', ...
                                'Position', [0.85 0 0.15 1], ...
                                'Callback', @(varargin) GetParamsFigure);
             
    % Note - due to MATLAB bug, if we set the component as Visible=off
    % during uicontrol creation, it will have the wrong look and feel
    % when we turn it back on
    set(reviewbutton, 'Visible', 'off');
end