%% ----------------------------------------------------------------------------------
% Post-analysis: Comparison of CBP to clustering results, and to ground truth (if
% available)

%** indicate which cells match ground truth.

function TimingComparisonMain
global CBPdata params CBPInternals;

%% ----------------------------------------------------------------------------------
% Post-analysis: Comparison of CBP to clustering results, and to ground truth (if
% available)

%** indicate which cells match ground truth.

if isfield(CBPdata.groundtruth, 'true_spike_times') && ...
   isfield(CBPdata.groundtruth, 'true_spike_class')
    % Reformat as 1-cellarr per cell of spike times.
    CBPdata.groundtruth.true_sp = GetSpikeTimesFromAssignments(...
        CBPdata.groundtruth.true_spike_times, ...
        CBPdata.groundtruth.true_spike_class);

    % Reorder to match cell numbering from clustering.
    [CBPdata.groundtruth.true_sp, ...
     CBPdata.groundtruth.true_spike_times, ...
     CBPdata.groundtruth.true_spike_class] = ReorderCells( ...
        CBPdata.groundtruth.true_sp, ...
        CBPdata.clustering.spike_times_cl, ...
        params.amplitude.spike_location_slack);

    % Since we already permuted ground truth to match clustering, this is true by
    % definition
    best_ordering_cl = 1:length(CBPdata.clustering.spike_times_cl);
    best_ordering = 1:length(CBPdata.CBP.spike_times);

    % Evaluate clustering sorting
    [total_misses_cl, total_false_positives_cl, misses_cl, ...
     false_positives_cl] = EvaluateSortingLowLevel( ...
          CBPdata.clustering.spike_times_cl, ...
          CBPdata.groundtruth.true_sp, ...
          params.amplitude.spike_location_slack);
    fprintf('Clustering: %s', SortingEvaluationStr( ...
          CBPdata.groundtruth.true_sp, ...
          CBPdata.clustering.spike_times_cl, ...
          total_misses_cl, total_false_positives_cl));

    % Evaluate CBP sorting
    [total_misses, total_false_positives, prune_est_times, misses, ...
     false_positives] = EvaluateSorting(CBPdata.CBP.spike_times, ...
          CBPdata.CBP.spike_amps, CBPdata.groundtruth.true_sp, ...
          'threshold', CBPdata.amplitude.amp_thresholds, ...
          'location_slack', params.amplitude.spike_location_slack);
    fprintf('       CBP: %s', SortingEvaluationStr( ...
          CBPdata.groundtruth.true_sp, prune_est_times, total_misses, ...
          total_false_positives));
end


%% -------------------------------------------------------------------------
% Quick addendum about ground truth

if ~isfield(CBPdata.groundtruth,'true_spike_times')
    fprintf('\nNOTE - file does not contain all ground truth information.\n')
    fprintf('Some of the next stages require ground truth; these will be skipped.\n\n')
end
