% Creates the parameter UI panel for a particular param field.
% This is called by CreateParamsFigure.
% The second parameter is the parent tab to attach the panel to.

function p = CreateParamsPanel(fieldname, parent)
    global params;

    % First construct uipanel
    p = uipanel('Parent', parent, ...
                'Tag', ['params_panel_' fieldname], ...
                'Units', 'normalized', ...
                'Position', [0 0 1 1]);
    RegisterTag(p);

    % Now add textboxes for each field
    field = getfield(params,fieldname);
    subfields = fieldnames(field);
    for n=1:length(subfields)
        subfieldname = subfields(n);
        subfieldname = subfieldname{1};
        
        % use "___" as a placeholder for "." in the tag, since "." isn't
        % permitted in field names
        subfieldlabel = uicontrol('Parent', p, ...
                                  'Tag', ['params_label_params___' fieldname '___' subfieldname], ...
                                  'Style', 'edit', ...
                                  'Enable', 'inactive', ...
                                  'String', subfieldname, ...
                                  'HorizontalAlignment', 'right', ...
                                  'Units', 'normalized', ...
                                  'Position', [.05 1-.06*n .35 .05], ...
                                  'FontUnits', 'normalized', ...
                                  'FontSize', .67);

        subfieldentry = uicontrol('Parent', p, ...
                                  'Tag', ['params_value_params___' fieldname '___' subfieldname], ...
                                  'Style', 'edit', ...
                                  'String', ConvertParamToStr(getfield(field,subfieldname)), ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'Position', [.4125 1-.06*n .55 .05], ...
                                  'FontUnits', 'normalized', ...
                                  'FontSize', .67, ...
                                  'Callback', @ParamChanged);
    RegisterTag(subfieldlabel);
    RegisterTag(subfieldentry);
    end
end
