% Creates the params status bar.  You probably don't want to call this
% directly, but rather GetCalibrationStatus (which calls this).

function h = CreateParamsStatus
    global params;

    h = uipanel(figure(params.plotting.params_figure), ...
                'Tag', 'params_sb', ...
                'Position', [0 0 1 0.075]);
    RegisterTag(h);

    sb_reset = uicontrol(h, 'Tag', 'params_sb_reset', ...
                            'Style', 'pushbutton', ...
                            'FontSize', 14, ...
                            'String', 'Reset', ...
                            'Units', 'normalized', ...
                            'Position', [0.5 0 0.25 1], ...
                            'Callback', @(varargin) ResetParamsFigure);
    sb_save  = uicontrol(h, 'Tag', 'params_sb_save', ...
                            'Style', 'pushbutton', ...
                            'FontSize', 14, ...
                            'String', 'Save', ...
                            'Units', 'normalized', ...
                            'Position', [0.75 0 0.25 1], ...
                            'Callback', @(varargin) SaveParams);
    RegisterTag(sb_reset);
    RegisterTag(sb_save);

    % add blank list of changed params to figure app data
    setappdata(figure(params.plotting.params_figure), 'changed', {});
end